- name: configure shipping component
  become: yes
  hosts: shipping
  tasks:
  - name: Install maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
  
  - name: Add Roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip
  
  - name: unzip shipping file
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: Rename shipping jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  - name: Daemon Reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: Start and Enable shipping service
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: Load the data into database
    community.mysql.mysql_db:
      login_user: root
      login_password: RoboShop@1
      name: all
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
    
  - name: Restart shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
